# Admin — https://guiders-admin.ancoradual.com

server {
    listen 80;
    listen [::]:80;
    server_name guiders-admin.ancoradual.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    root /var/www/guiders-frontend/current/admin;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
